# Generated by Django 3.2 on 2021-04-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('paid', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('gov_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('BOG', 'BOGOTA'), ('BARR', 'BARRANQUILLA'), ('CART', 'CARTAGENA'), ('CAL', 'CALI'), ('MED', 'MEDELLIN')], default='MED', max_length=4)),
                ('state', models.CharField(choices=[('ANT', 'ANTIOQUIA'), ('ATL', 'ATLANTICO'), ('BOL', 'BOLIVAR'), ('CUND', 'CUNDINAMARCA'), ('VAC', 'VALLE DEL CAUCA')], default='ANT', max_length=4)),
                ('country', models.CharField(choices=[('COL', 'COLOMBIA')], default='COL', max_length=4)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(choices=[('CCARD', 'CREDIT CARD'), ('DEBIT', 'PSE')], default='CCARD', max_length=5)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('APR', 'APROBADO'), ('CANC', 'CANCELADA'), ('RECH', 'RECHAZADO')], max_length=4)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='gov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
